// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPCpZxh4MIBZHwiraxIyqf0HxBoaXaudw',
    appId: '1:291006781124:web:22d17a6dfacef26f889b91',
    messagingSenderId: '291006781124',
    projectId: 'authenticationproject-7d81a',
    authDomain: 'authenticationproject-7d81a.firebaseapp.com',
    storageBucket: 'authenticationproject-7d81a.appspot.com',
    measurementId: 'G-SE18NVW3M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_E1UP6hke-ClKwSKq3_0NYQxQJ_4oWjE',
    appId: '1:291006781124:android:95843de69a587586889b91',
    messagingSenderId: '291006781124',
    projectId: 'authenticationproject-7d81a',
    storageBucket: 'authenticationproject-7d81a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBThoo0paGmqKFaDAFsOnaXLDHsYWiv0vQ',
    appId: '1:291006781124:ios:86778f1d39ada104889b91',
    messagingSenderId: '291006781124',
    projectId: 'authenticationproject-7d81a',
    storageBucket: 'authenticationproject-7d81a.appspot.com',
    iosBundleId: 'com.example.authenticationProject',
  );
}
